export const APPLY_FILTERS = 'APPLY_FILTERS';
export const LOAD_MORE = 'LOAD_MORE';
export const REQUEST_AIRPORTS = 'REQUEST_AIRPORTS';
export const RECEIVE_AIRPORTS = 'RECEIVE_AIRPORTS';
export const RECEIVE_TYPES = 'RECEIVE_TYPES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';